name: Deploy to Hugging Face Hub

# Déclencheur : se lance à chaque push sur la branche 'main'
on:
  push:
    branches:
      - main

# Variables d'environnement pour tout le job, pour la propreté
env:
  HF_MODEL_REPO: ${{ secrets.GITHUB_REPOSITORY }}
  MODEL_FILENAME: model.joblib
  
jobs:
  deploy:
    name: Train and Deploy Model
    runs-on: ubuntu-latest # Utilise une machine virtuelle Linux à jour
    
    steps:
      # Étape 1: Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3
        # On récupère l'historique complet pour que LFS fonctionne correctement
        with:
          fetch-depth: 0 
          
      # Étape 3: Mettre en place l'environnement Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Spécifier une version pour la reproductibilité
          
      # Étape 4: Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 5: Entraîner le modèle
      # Cette étape génère l'artefact (le modèle) qui sera déployé.
      - name: Train model
        run: python model.py --action train
        
      # Étape 6: Pousser le modèle vers Hugging Face Hub
      # L'approche la plus moderne et robuste est d'utiliser la bibliothèque Python `huggingface_hub`.
      - name: Push to Hugging Face Hub
        env:
          # Le token est passé en variable d'environnement pour cette étape
          HUGGING_FACE_HUB_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "
          from huggingface_hub import HfApi, HfFolder
          
          # Authentification (plus nécessaire si le token est dans l'env)
          # HfFolder.save_token('${{ secrets.HF_TOKEN }}')
          
          api = HfApi()
          
          # Push du fichier de modèle
          api.upload_file(
              path_or_fileobj=f'./{_env['MODEL_FILENAME']}',
              path_in_repo=f'{_env['MODEL_FILENAME']}',
              repo_id=_env['HF_MODEL_REPO'],
              repo_type='model'
          )
          
          # Push du README
          api.upload_file(
              path_or_fileobj='./README.md',
              path_in_repo='README.md',
              repo_id=_env['HF_MODEL_REPO'],
              repo_type='model'
          )
          
          print('Fichiers poussés avec succès sur le Hub !')
          "