# .github/workflows/deploy-to-hf.yml

name: Deploy to Hugging Face Hub

on:
  push:
    branches:
      - main

# Pas de variables d'environnement globales pour le repo_id pour éviter les conflits.
# Nous les définirons au niveau du job ou de la step pour plus de clarté.
env:
  MODEL_FILENAME: model.joblib
  PYTHON_VERSION: '3.9'

jobs:
  deploy:
    name: Train and Deploy Model
    runs-on: ubuntu-latest
    
    # Définition des variables d'environnement spécifiques à ce job
    env:
      # CORRECTION FINALE : On utilise la source de vérité garantie.
      # github.repository contient TOUJOURS le format 'namespace/repo_name'.
      HF_REPO_ID: ${{ github.repository }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: python model.py --action train
      
      - name: Push to Hugging Face Hub
        env:
          # On passe le token secret uniquement à cette étape
          HUGGING_FACE_HUB_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "
          from huggingface_hub import HfApi
          import os

          # Le script lit les variables d'environnement du job et de la step
          repo_id = os.getenv('HF_REPO_ID')
          model_filename = os.getenv('MODEL_FILENAME')
          
          print(f'Déploiement sur le dépôt : {repo_id}')
          print(f'Fichier modèle à pousser : {model_filename}')

          api = HfApi()

          print('Création (si besoin) du dépôt sur le Hub...')
          api.create_repo(
              repo_id=repo_id,
              repo_type='model',
              exist_ok=True
          )
          print('Dépôt prêt.')

          print('Début du push des fichiers...')
          api.upload_file(
              path_or_fileobj=f'./{model_filename}',
              path_in_repo=model_filename,
              repo_id=repo_id,
              repo_type='model'
          )
          
          api.upload_file(
              path_or_fileobj='./README.md',
              path_in_repo='README.md',
              repo_id=repo_id,
              repo_type='model'
          )
          
          print('Fichiers poussés avec succès sur le Hub !')
          "

  notify_on_success:
    name: Send Success Notification
    runs-on: ubuntu-latest
    needs: deploy
    
    steps:
      - name: Send deployment success email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER_ADDRESS }}
          server_port: ${{ secrets.MAIL_SERVER_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 'Succès du Déploiement : ${{ github.repository }}'
          to: ${{ secrets.MAIL_USERNAME }}
          from: GitHub Actions <${{ secrets.MAIL_USERNAME }}>
          body: |
            Bonjour,

            Le déploiement du modèle sur le dépôt ${{ github.repository }} a réussi.
            
            Commit : ${{ github.sha }}
            Auteur : ${{ github.actor }}
            
            Le modèle a été déployé avec succès et est disponible sur Hugging Face Hub :
            https://huggingface.co/${{ github.repository }}

            Cordialement,
            Votre Pipeline CI/CD.